name: Tests

on: [ push ]

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: true
            matrix:
                php: [ 7.3, 8.0 ]
                laravel: [ 6.*, 7.*, 8.*, 9.* ]
                stability: [ prefer-lowest, prefer-stable ]
                include:
                    -   laravel: 6.*
                        php: 7.3
                    -   laravel: 7.*
                        php: 7.3
                    -   laravel: 8.*
                        php: 7.3
                    -   laravel: 9.*
                        php: 8.0

        name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, fileinfo
                    coverage: none

            -   name: Install dependencies
                run: |
                    composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update
                    composer update --${{ matrix.stability }} --prefer-dist --no-interaction

            -   name: Execute tests
                run: vendor/bin/phpunit
